set -g mouse on

# Set terminal window title to match PS1 format
set-option -g set-titles on
set-option -g set-titles-string "#{pane_title}"

# Also set window names in byobu
set-option -g automatic-rename on
set -g allow-rename on

# Use vi-style keybindings in copy mode
set -g mode-keys vi

# Copy mouse selection to system clipboard (Linux with xsel)
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "xsel -i -b"


# Optional: Keyboard binding for copying with 'y'
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -i -b"

set-option -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'

set -g bell-action none

# Disable pane info line (tmux 3.3+)
set -g status-format[1] ""

